#!/usr/bin/env bash

echo "== put-object"

# Check for bucket name
if [ -z "$1" ]; then
  echo "Error: There needs to be a bucket name eg. ./bucket my-bucket-name"
  exit 1
fi

# Check for filename 
if [ -z "$2" ]; then
  echo "Error: There needs to be a filename eg. ./bucket my-bucket-name my-filename"
  exit 1
fi

BUCKET_NAME="$1"
FILE_PATH="$2"

# Extract just the filename (e.g. "myfile.txt" from "/tmp/myfile.txt") to use as the S3 Key
OBJECT_KEY=$(basename "$FILE_PATH")

aws s3api put-object \
--bucket "$BUCKET_NAME" \
--key "$OBJECT_KEY" \
--body "$FILE_PATH"

