#!/usr/bin/env bash

 echo "== delete stack"


 STACK_NAME='cfn-s3-simple'
 REGION='ca-central-1'

 aws cloudformation delete-stack \
 --stack-name $STACK_NAME \
 --region $REGION

echo "Stack deleted successfully!"
